const usetube = require('../dist/usetube.min.js')
let test = async function() {
//   let wow = await fetch('https://www.youtube.com/channel/UCcdNy_FqMi0z1VU6kanOvFQ/')
//   let wow = await usetube.getChannelVideos('UCp5KUL1Mb7Kpfw10SGyPumQ')
  // let wow = await usetube.getChannelVideos('UC6eCu3YVjhlB1mjRILyw0tQ')
  // let wow = await usetube.getVideoDesc('TupbkwAkRb8')
//   let wow = await usetube.getChannelDesc('UCp5KUL1Mb7Kpfw10SGyPumQ')
//   let wow = await usetube.searchChannel('noisiaa')
  let wow = await usetube.searchVideo('IMANU - Music To Stay In Your House To (Buunshin’s Go Outside Remix)')
  // let wow = await usetube.getVideoDate('i0Q0HIpvkhU')
  // let wow = await usetube.getPlaylistVideos('PLKuN-WEIzl_pwo3US7XyZJe1oVCD7NLwF', true)
  // let wow = await usetube.getTracksFromDesc('ip_ght29b_A')
  // let wow = await usetube.getVideosFromDesc('W6NKM2PcPdI')
  console.log(wow)
  console.log(wow.length)
}
test()
